version: '3.8'

services:
  # AgentOS Application
  agent-os:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Database
      - DATABASE_URL=sqlite:///app/promo_creator.db

      # API Keys (set these in your environment)
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - PEXELS_API_KEY=${PEXELS_API_KEY}

      # AgentOS Configuration
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000

    volumes:
      # Persist SQLite database
      - agent_data:/app/data

    restart: unless-stopped

    depends_on:
      - postgres

    networks:
      - agent_network

  # PostgreSQL Database (Optional - for production)
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=ai_promo_creator
      - POSTGRES_USER=agno_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-agno_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - agent_network

  # Redis (Optional - for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - agent_network

volumes:
  agent_data:
  postgres_data:
  redis_data:

networks:
  agent_network:
    driver: bridge